repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        # args: [--assume-in-merge]
        fail_fast: true
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      # - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-docstring-first
      # - id: name-tests-test
      #   args: [--django]
  - repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.3
    hooks:
      - id: sync-pre-commit-deps
  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.10.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: [--ignore-path=.prettierignore]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
      - id: black-jupyter
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: [--recursive, --quiet, --config, bandit.yaml]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8 # E***, W***, F***
        additional_dependencies:
          - dlint # DUO***
          - flake8-2020 # YTT***
          - flake8-bugbear # B***
          - flake8-builtins # A***
          - flake8-comprehensions # C4**
          - flake8-deprecated # D***
          - flake8-variables-names # VNE***
          - mccabe # C9**
          - pep8-naming # N8**
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.10.0
#    hooks:
#      - id: mypy
